In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
import joblib
import pickle

In [3]:
df = pd.read_csv("dataset.csv")
pd.set_option("display.max_columns", None)
df

Disease  Symptom_1  Symptom_2  \
0     (vertigo) Paroymsal  Positional Vertigo   vomiting   headache   
1     (vertigo) Paroymsal  Positional Vertigo        NaN   headache   
2     (vertigo) Paroymsal  Positional Vertigo   vomiting        NaN   
3     (vertigo) Paroymsal  Positional Vertigo   vomiting   headache   
4     (vertigo) Paroymsal  Positional Vertigo   vomiting   headache   
...                                       ...        ...        ...   
4915                           Varicose veins    fatigue     cramps   
4916                           Varicose veins    fatigue     cramps   
4917                           Varicose veins    fatigue     cramps   
4918                           Varicose veins    fatigue     cramps   
4919                           Varicose veins    fatigue     cramps   

      Symptom_3            Symptom_4         Symptom_5  \
0        nausea   spinning_movements   loss_of_balance   
1        nausea   spinning_movements   loss_of_balance   
2        nausea   spinning_movements   loss_of_balance   
3           NaN   spinning_movements   loss_of_balance   
4        nausea                  NaN   loss_of_balance   
...         ...                  ...               ...   
4915   bruising              obesity      swollen_legs   
4916   bruising              obesity      swollen_legs   
4917   bruising              obesity      swollen_legs   
4918   bruising              obesity      swollen_legs   
4919   bruising              obesity      swollen_legs   

                   Symptom_6                 Symptom_7 Symptom_8 Symptom_9  \
0               unsteadiness                       NaN       NaN       NaN   
1               unsteadiness                       NaN       NaN       NaN   
2               unsteadiness                       NaN       NaN       NaN   
3               unsteadiness                       NaN       NaN       NaN   
4               unsteadiness                       NaN       NaN       NaN   
...                      ...                       ...       ...       ...   
4915   swollen_blood_vessels   prominent_veins_on_calf       NaN       NaN   
4916   swollen_blood_vessels   prominent_veins_on_calf       NaN       NaN   
4917   swollen_blood_vessels   prominent_veins_on_calf       NaN       NaN   
4918   swollen_blood_vessels   prominent_veins_on_calf       NaN       NaN   
4919   swollen_blood_vessels   prominent_veins_on_calf       NaN       NaN   

     Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0           NaN        NaN        NaN        NaN        NaN        NaN   
1           NaN        NaN        NaN        NaN        NaN        NaN   
2           NaN        NaN        NaN        NaN        NaN        NaN   
3           NaN        NaN        NaN        NaN        NaN        NaN   
4           NaN        NaN        NaN        NaN        NaN        NaN   
...         ...        ...        ...        ...        ...        ...   
4915        NaN        NaN        NaN        NaN        NaN        NaN   
4916        NaN        NaN        NaN        NaN        NaN        NaN   
4917        NaN        NaN        NaN        NaN        NaN        NaN   
4918        NaN        NaN        NaN        NaN        NaN        NaN   
4919        NaN        NaN        NaN        NaN        NaN        NaN   

     Symptom_16 Symptom_17  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
4915        NaN        NaN  
4916        NaN        NaN  
4917        NaN        NaN  
4918        NaN        NaN  
4919        NaN        NaN  

[4920 rows x 18 columns]

In [4]:
df.isnull().sum()

Disease          1
Symptom_1      300
Symptom_2      343
Symptom_3      316
Symptom_4      285
Symptom_5     1176
Symptom_6     1854
Symptom_7     2644
Symptom_8     2952
Symptom_9     3151
Symptom_10    3371
Symptom_11    3493
Symptom_12    4086
Symptom_13    4326
Symptom_14    4566
Symptom_15    4680
Symptom_16    4680
Symptom_17    4800
dtype: int64

In [5]:
cols = [i for i in df.iloc[:,1:].columns]
tmp = pd.melt(df.reset_index() ,id_vars = ['index'], value_vars = cols )
tmp['found'] = 1
tmp.head(40)

index   variable      value  found
0       0  Symptom_1   vomiting      1
1       1  Symptom_1        NaN      1
2       2  Symptom_1   vomiting      1
3       3  Symptom_1   vomiting      1
4       4  Symptom_1   vomiting      1
5       5  Symptom_1   vomiting      1
6       6  Symptom_1   vomiting      1
7       7  Symptom_1   vomiting      1
8       8  Symptom_1   vomiting      1
9       9  Symptom_1   vomiting      1
10     10  Symptom_1   vomiting      1
11     11  Symptom_1        NaN      1
12     12  Symptom_1   vomiting      1
13     13  Symptom_1   vomiting      1
14     14  Symptom_1   vomiting      1
15     15  Symptom_1   vomiting      1
16     16  Symptom_1   vomiting      1
17     17  Symptom_1   vomiting      1
18     18  Symptom_1   vomiting      1
19     19  Symptom_1   vomiting      1
20     20  Symptom_1   vomiting      1
21     21  Symptom_1        NaN      1
22     22  Symptom_1   vomiting      1
23     23  Symptom_1   vomiting      1
24     24  Symptom_1   vomiting      1
25     25  Symptom_1   vomiting      1
26     26  Symptom_1   vomiting      1
27     27  Symptom_1   vomiting      1
28     28  Symptom_1   vomiting      1
29     29  Symptom_1   vomiting      1
30     30  Symptom_1   vomiting      1
31     31  Symptom_1        NaN      1
32     32  Symptom_1   vomiting      1
33     33  Symptom_1   vomiting      1
34     34  Symptom_1   vomiting      1
35     35  Symptom_1   vomiting      1
36     36  Symptom_1   vomiting      1
37     37  Symptom_1   vomiting      1
38     38  Symptom_1   vomiting      1
39     39  Symptom_1   vomiting      1

In [6]:
newdf = pd.pivot_table(tmp, 
                          values = 'found',
                          index = 'index',
                          columns = 'value')
newdf.insert(0,'label',df['Disease'])
newdf = newdf.fillna(0)
newdf

value                                    label   abdominal_pain  \
index                                                             
0      (vertigo) Paroymsal  Positional Vertigo              0.0   
1      (vertigo) Paroymsal  Positional Vertigo              0.0   
2      (vertigo) Paroymsal  Positional Vertigo              0.0   
3      (vertigo) Paroymsal  Positional Vertigo              0.0   
4      (vertigo) Paroymsal  Positional Vertigo              0.0   
...                                        ...              ...   
4915                            Varicose veins              0.0   
4916                            Varicose veins              0.0   
4917                            Varicose veins              0.0   
4918                            Varicose veins              0.0   
4919                            Varicose veins              0.0   

value   abnormal_menstruation   acidity   acute_liver_failure  \
index                                                           
0                         0.0       0.0                   0.0   
1                         0.0       0.0                   0.0   
2                         0.0       0.0                   0.0   
3                         0.0       0.0                   0.0   
4                         0.0       0.0                   0.0   
...                       ...       ...                   ...   
4915                      0.0       0.0                   0.0   
4916                      0.0       0.0                   0.0   
4917                      0.0       0.0                   0.0   
4918                      0.0       0.0                   0.0   
4919                      0.0       0.0                   0.0   

value   altered_sensorium   anxiety   back_pain   belly_pain   blackheads  \
index                                                                       
0                     0.0       0.0         0.0          0.0          0.0   
1                     0.0       0.0         0.0          0.0          0.0   
2                     0.0       0.0         0.0          0.0          0.0   
3                     0.0       0.0         0.0          0.0          0.0   
4                     0.0       0.0         0.0          0.0          0.0   
...                   ...       ...         ...          ...          ...   
4915                  0.0       0.0         0.0          0.0          0.0   
4916                  0.0       0.0         0.0          0.0          0.0   
4917                  0.0       0.0         0.0          0.0          0.0   
4918                  0.0       0.0         0.0          0.0          0.0   
4919                  0.0       0.0         0.0          0.0          0.0   

value   bladder_discomfort   blister   blood_in_sputum   bloody_stool  \
index                                                                   
0                      0.0       0.0               0.0            0.0   
1                      0.0       0.0               0.0            0.0   
2                      0.0       0.0               0.0            0.0   
3                      0.0       0.0               0.0            0.0   
4                      0.0       0.0               0.0            0.0   
...                    ...       ...               ...            ...   
4915                   0.0       0.0               0.0            0.0   
4916                   0.0       0.0               0.0            0.0   
4917                   0.0       0.0               0.0            0.0   
4918                   0.0       0.0               0.0            0.0   
4919                   0.0       0.0               0.0            0.0   

value   blurred_and_distorted_vision   breathlessness   brittle_nails  \
index                                                                   
0                                0.0              0.0             0.0   
1                                0.0              0.0             0.0   
2                                0.0  

In [7]:
X = newdf.drop('label',axis=1)
y = newdf['label']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0, stratify=y)

In [11]:
rfc = CatBoostClassifier(iterations=2000, eval_metric = "AUC")
rfc.fit(X_train, y_train)

Learning rate set to 0.047083
0:	total: 197ms	remaining: 6m 34s
1:	total: 243ms	remaining: 4m 3s
2:	total: 288ms	remaining: 3m 11s
3:	total: 337ms	remaining: 2m 47s
4:	total: 388ms	remaining: 2m 34s
5:	total: 436ms	remaining: 2m 24s
6:	total: 486ms	remaining: 2m 18s
7:	total: 534ms	remaining: 2m 12s
8:	total: 579ms	remaining: 2m 8s
9:	total: 624ms	remaining: 2m 4s
10:	total: 675ms	remaining: 2m 2s
11:	total: 722ms	remaining: 1m 59s
12:	total: 765ms	remaining: 1m 57s
13:	total: 812ms	remaining: 1m 55s
14:	total: 853ms	remaining: 1m 52s
15:	total: 895ms	remaining: 1m 50s
16:	total: 939ms	remaining: 1m 49s
17:	total: 987ms	remaining: 1m 48s
18:	total: 1.03s	remaining: 1m 47s
19:	total: 1.07s	remaining: 1m 46s
20:	total: 1.11s	remaining: 1m 45s
21:	total: 1.16s	remaining: 1m 44s
22:	total: 1.21s	remaining: 1m 44s
23:	total: 1.25s	remaining: 1m 43s
24:	total: 1.29s	remaining: 1m 42s
25:	total: 1.34s	remaining: 1m 41s
26:	total: 1.39s	remaining: 1m 41s
27:	total: 1.43s	remaining: 1m 40s
28:	

234:	total: 10.7s	remaining: 1m 20s
235:	total: 10.8s	remaining: 1m 20s
236:	total: 10.8s	remaining: 1m 20s
237:	total: 10.9s	remaining: 1m 20s
238:	total: 10.9s	remaining: 1m 20s
239:	total: 11s	remaining: 1m 20s
240:	total: 11s	remaining: 1m 20s
241:	total: 11s	remaining: 1m 20s
242:	total: 11.1s	remaining: 1m 20s
243:	total: 11.1s	remaining: 1m 20s
244:	total: 11.2s	remaining: 1m 20s
245:	total: 11.2s	remaining: 1m 19s
246:	total: 11.3s	remaining: 1m 19s
247:	total: 11.3s	remaining: 1m 19s
248:	total: 11.3s	remaining: 1m 19s
249:	total: 11.4s	remaining: 1m 19s
250:	total: 11.4s	remaining: 1m 19s
251:	total: 11.5s	remaining: 1m 19s
252:	total: 11.5s	remaining: 1m 19s
253:	total: 11.6s	remaining: 1m 19s
254:	total: 11.6s	remaining: 1m 19s
255:	total: 11.7s	remaining: 1m 19s
256:	total: 11.7s	remaining: 1m 19s
257:	total: 11.8s	remaining: 1m 19s
258:	total: 11.8s	remaining: 1m 19s
259:	total: 11.9s	remaining: 1m 19s
260:	total: 11.9s	remaining: 1m 19s
261:	total: 11.9s	remaining: 1m 19

466:	total: 20.9s	remaining: 1m 8s
467:	total: 21s	remaining: 1m 8s
468:	total: 21s	remaining: 1m 8s
469:	total: 21.1s	remaining: 1m 8s
470:	total: 21.1s	remaining: 1m 8s
471:	total: 21.2s	remaining: 1m 8s
472:	total: 21.2s	remaining: 1m 8s
473:	total: 21.3s	remaining: 1m 8s
474:	total: 21.3s	remaining: 1m 8s
475:	total: 21.4s	remaining: 1m 8s
476:	total: 21.4s	remaining: 1m 8s
477:	total: 21.5s	remaining: 1m 8s
478:	total: 21.5s	remaining: 1m 8s
479:	total: 21.5s	remaining: 1m 8s
480:	total: 21.6s	remaining: 1m 8s
481:	total: 21.6s	remaining: 1m 8s
482:	total: 21.7s	remaining: 1m 8s
483:	total: 21.7s	remaining: 1m 8s
484:	total: 21.8s	remaining: 1m 7s
485:	total: 21.8s	remaining: 1m 7s
486:	total: 21.8s	remaining: 1m 7s
487:	total: 21.9s	remaining: 1m 7s
488:	total: 21.9s	remaining: 1m 7s
489:	total: 22s	remaining: 1m 7s
490:	total: 22s	remaining: 1m 7s
491:	total: 22.1s	remaining: 1m 7s
492:	total: 22.1s	remaining: 1m 7s
493:	total: 22.2s	remaining: 1m 7s
494:	total: 22.2s	remaining:

705:	total: 31.5s	remaining: 57.8s
706:	total: 31.6s	remaining: 57.7s
707:	total: 31.6s	remaining: 57.7s
708:	total: 31.6s	remaining: 57.6s
709:	total: 31.7s	remaining: 57.6s
710:	total: 31.7s	remaining: 57.5s
711:	total: 31.8s	remaining: 57.5s
712:	total: 31.8s	remaining: 57.5s
713:	total: 31.9s	remaining: 57.4s
714:	total: 31.9s	remaining: 57.4s
715:	total: 32s	remaining: 57.3s
716:	total: 32s	remaining: 57.3s
717:	total: 32.1s	remaining: 57.2s
718:	total: 32.1s	remaining: 57.2s
719:	total: 32.1s	remaining: 57.2s
720:	total: 32.2s	remaining: 57.1s
721:	total: 32.2s	remaining: 57.1s
722:	total: 32.3s	remaining: 57s
723:	total: 32.3s	remaining: 57s
724:	total: 32.4s	remaining: 56.9s
725:	total: 32.4s	remaining: 56.9s
726:	total: 32.5s	remaining: 56.8s
727:	total: 32.5s	remaining: 56.8s
728:	total: 32.6s	remaining: 56.8s
729:	total: 32.6s	remaining: 56.7s
730:	total: 32.7s	remaining: 56.7s
731:	total: 32.7s	remaining: 56.6s
732:	total: 32.7s	remaining: 56.6s
733:	total: 32.8s	remaining:

944:	total: 42s	remaining: 46.9s
945:	total: 42s	remaining: 46.8s
946:	total: 42.1s	remaining: 46.8s
947:	total: 42.1s	remaining: 46.7s
948:	total: 42.2s	remaining: 46.7s
949:	total: 42.2s	remaining: 46.6s
950:	total: 42.2s	remaining: 46.6s
951:	total: 42.3s	remaining: 46.5s
952:	total: 42.3s	remaining: 46.5s
953:	total: 42.4s	remaining: 46.5s
954:	total: 42.4s	remaining: 46.4s
955:	total: 42.4s	remaining: 46.4s
956:	total: 42.5s	remaining: 46.3s
957:	total: 42.5s	remaining: 46.3s
958:	total: 42.6s	remaining: 46.2s
959:	total: 42.6s	remaining: 46.2s
960:	total: 42.7s	remaining: 46.1s
961:	total: 42.7s	remaining: 46.1s
962:	total: 42.7s	remaining: 46s
963:	total: 42.8s	remaining: 46s
964:	total: 42.8s	remaining: 45.9s
965:	total: 42.9s	remaining: 45.9s
966:	total: 42.9s	remaining: 45.8s
967:	total: 43s	remaining: 45.8s
968:	total: 43s	remaining: 45.7s
969:	total: 43s	remaining: 45.7s
970:	total: 43.1s	remaining: 45.7s
971:	total: 43.1s	remaining: 45.6s
972:	total: 43.2s	remaining: 45.6s

1176:	total: 51.9s	remaining: 36.3s
1177:	total: 51.9s	remaining: 36.2s
1178:	total: 52s	remaining: 36.2s
1179:	total: 52s	remaining: 36.1s
1180:	total: 52.1s	remaining: 36.1s
1181:	total: 52.1s	remaining: 36.1s
1182:	total: 52.1s	remaining: 36s
1183:	total: 52.2s	remaining: 36s
1184:	total: 52.2s	remaining: 35.9s
1185:	total: 52.3s	remaining: 35.9s
1186:	total: 52.3s	remaining: 35.8s
1187:	total: 52.4s	remaining: 35.8s
1188:	total: 52.4s	remaining: 35.7s
1189:	total: 52.4s	remaining: 35.7s
1190:	total: 52.5s	remaining: 35.6s
1191:	total: 52.5s	remaining: 35.6s
1192:	total: 52.6s	remaining: 35.6s
1193:	total: 52.6s	remaining: 35.5s
1194:	total: 52.7s	remaining: 35.5s
1195:	total: 52.7s	remaining: 35.4s
1196:	total: 52.7s	remaining: 35.4s
1197:	total: 52.8s	remaining: 35.3s
1198:	total: 52.8s	remaining: 35.3s
1199:	total: 52.9s	remaining: 35.2s
1200:	total: 52.9s	remaining: 35.2s
1201:	total: 52.9s	remaining: 35.1s
1202:	total: 53s	remaining: 35.1s
1203:	total: 53s	remaining: 35.1s
1204

1412:	total: 1m 2s	remaining: 25.8s
1413:	total: 1m 2s	remaining: 25.8s
1414:	total: 1m 2s	remaining: 25.8s
1415:	total: 1m 2s	remaining: 25.7s
1416:	total: 1m 2s	remaining: 25.7s
1417:	total: 1m 2s	remaining: 25.6s
1418:	total: 1m 2s	remaining: 25.6s
1419:	total: 1m 2s	remaining: 25.5s
1420:	total: 1m 2s	remaining: 25.5s
1421:	total: 1m 2s	remaining: 25.4s
1422:	total: 1m 2s	remaining: 25.4s
1423:	total: 1m 2s	remaining: 25.4s
1424:	total: 1m 2s	remaining: 25.3s
1425:	total: 1m 2s	remaining: 25.3s
1426:	total: 1m 2s	remaining: 25.2s
1427:	total: 1m 2s	remaining: 25.2s
1428:	total: 1m 2s	remaining: 25.1s
1429:	total: 1m 2s	remaining: 25.1s
1430:	total: 1m 3s	remaining: 25.1s
1431:	total: 1m 3s	remaining: 25s
1432:	total: 1m 3s	remaining: 25s
1433:	total: 1m 3s	remaining: 24.9s
1434:	total: 1m 3s	remaining: 24.9s
1435:	total: 1m 3s	remaining: 24.8s
1436:	total: 1m 3s	remaining: 24.8s
1437:	total: 1m 3s	remaining: 24.8s
1438:	total: 1m 3s	remaining: 24.7s
1439:	total: 1m 3s	remaining: 24

1644:	total: 1m 12s	remaining: 15.6s
1645:	total: 1m 12s	remaining: 15.6s
1646:	total: 1m 12s	remaining: 15.5s
1647:	total: 1m 12s	remaining: 15.5s
1648:	total: 1m 12s	remaining: 15.4s
1649:	total: 1m 12s	remaining: 15.4s
1650:	total: 1m 12s	remaining: 15.3s
1651:	total: 1m 12s	remaining: 15.3s
1652:	total: 1m 12s	remaining: 15.3s
1653:	total: 1m 12s	remaining: 15.2s
1654:	total: 1m 12s	remaining: 15.2s
1655:	total: 1m 12s	remaining: 15.1s
1656:	total: 1m 12s	remaining: 15.1s
1657:	total: 1m 12s	remaining: 15s
1658:	total: 1m 12s	remaining: 15s
1659:	total: 1m 12s	remaining: 14.9s
1660:	total: 1m 13s	remaining: 14.9s
1661:	total: 1m 13s	remaining: 14.9s
1662:	total: 1m 13s	remaining: 14.8s
1663:	total: 1m 13s	remaining: 14.8s
1664:	total: 1m 13s	remaining: 14.7s
1665:	total: 1m 13s	remaining: 14.7s
1666:	total: 1m 13s	remaining: 14.6s
1667:	total: 1m 13s	remaining: 14.6s
1668:	total: 1m 13s	remaining: 14.6s
1669:	total: 1m 13s	remaining: 14.5s
1670:	total: 1m 13s	remaining: 14.5s
1671:

1870:	total: 1m 22s	remaining: 5.68s
1871:	total: 1m 22s	remaining: 5.63s
1872:	total: 1m 22s	remaining: 5.59s
1873:	total: 1m 22s	remaining: 5.54s
1874:	total: 1m 22s	remaining: 5.5s
1875:	total: 1m 22s	remaining: 5.46s
1876:	total: 1m 22s	remaining: 5.41s
1877:	total: 1m 22s	remaining: 5.37s
1878:	total: 1m 22s	remaining: 5.33s
1879:	total: 1m 22s	remaining: 5.28s
1880:	total: 1m 22s	remaining: 5.24s
1881:	total: 1m 22s	remaining: 5.19s
1882:	total: 1m 22s	remaining: 5.15s
1883:	total: 1m 22s	remaining: 5.1s
1884:	total: 1m 22s	remaining: 5.06s
1885:	total: 1m 22s	remaining: 5.02s
1886:	total: 1m 23s	remaining: 4.97s
1887:	total: 1m 23s	remaining: 4.93s
1888:	total: 1m 23s	remaining: 4.88s
1889:	total: 1m 23s	remaining: 4.84s
1890:	total: 1m 23s	remaining: 4.8s
1891:	total: 1m 23s	remaining: 4.75s
1892:	total: 1m 23s	remaining: 4.71s
1893:	total: 1m 23s	remaining: 4.66s
1894:	total: 1m 23s	remaining: 4.62s
1895:	total: 1m 23s	remaining: 4.58s
1896:	total: 1m 23s	remaining: 4.53s
1897

In [12]:
y_pred = rfc.predict(X_test)
print("Confustion Matrix:", confusion_matrix(y_test,y_pred))
print("Accuracy:", accuracy_score(y_test,y_pred)*100)
print(classification_report(y_test,y_pred))

Confustion Matrix: [[30  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 30 ...  0  0  0]
 ...
 [ 0  0  0 ... 30  0  0]
 [ 0  0  0 ...  0 30  0]
 [ 0  0  0 ...  0  0 30]]
Accuracy: 100.0
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        30
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        30
                    Alcoholic hepatitis       1.00      1.00      1.00        30
                                Allergy       1.00      1.00      1.00        30
                              Arthritis       1.00      1.00      1.00        30
                       Bronchial Asthma       1.00      1.00      1.00        30
                   Cervical spondylosis       1.00      1.00      1.00        30
                            Chicken pox       1.00      1.00      1.00        3

In [13]:
pd.DataFrame(y_pred, y_test)

0
label                                                                           
Paralysis (brain hemorrhage)                        Paralysis (brain hemorrhage)
Dengue                                                                    Dengue
(vertigo) Paroymsal  Positional Vertigo  (vertigo) Paroymsal  Positional Vertigo
Tuberculosis                                                        Tuberculosis
Hyperthyroidism                                                  Hyperthyroidism
...                                                                          ...
Cervical spondylosis                                        Cervical spondylosis
Chicken pox                                                          Chicken pox
AIDS                                                                        AIDS
Malaria                                                                  Malaria
Alcoholic hepatitis                                          Alcoholic hepatitis

[1230 rows x 1 columns]

In [14]:
lst = []
sym_dict = {}
for i in newdf.columns:
    sym_dict[i]=0
    lst.append(i)
print(sym_dict)

{'label': 0, ' abdominal_pain': 0, ' abnormal_menstruation': 0, ' acidity': 0, ' acute_liver_failure': 0, ' altered_sensorium': 0, ' anxiety': 0, ' back_pain': 0, ' belly_pain': 0, ' blackheads': 0, ' bladder_discomfort': 0, ' blister': 0, ' blood_in_sputum': 0, ' bloody_stool': 0, ' blurred_and_distorted_vision': 0, ' breathlessness': 0, ' brittle_nails': 0, ' bruising': 0, ' burning_micturition': 0, ' chest_pain': 0, ' chills': 0, ' cold_hands_and_feets': 0, ' coma': 0, ' congestion': 0, ' constipation': 0, ' continuous_feel_of_urine': 0, ' continuous_sneezing': 0, ' cough': 0, ' cramps': 0, ' dark_urine': 0, ' dehydration': 0, ' depression': 0, ' diarrhoea': 0, ' dischromic _patches': 0, ' distention_of_abdomen': 0, ' dizziness': 0, ' drying_and_tingling_lips': 0, ' enlarged_thyroid': 0, ' excessive_hunger': 0, ' extra_marital_contacts': 0, ' family_history': 0, ' fast_heart_rate': 0, ' fatigue': 0, ' fluid_overload': 0, ' foul_smell_of urine': 0, ' headache': 0, ' high_fever': 0, '

In [15]:
newdf.columns

Index(['label', ' abdominal_pain', ' abnormal_menstruation', ' acidity',
       ' acute_liver_failure', ' altered_sensorium', ' anxiety', ' back_pain',
       ' belly_pain', ' blackheads',
       ...
       ' watering_from_eyes', ' weakness_in_limbs',
       ' weakness_of_one_body_side', ' weight_gain', ' weight_loss',
       ' yellow_crust_ooze', ' yellow_urine', ' yellowing_of_eyes',
       ' yellowish_skin', 'itching'],
      dtype='object', name='value', length=132)

In [16]:
y_pred = rfc.predict_proba(X_test)

In [17]:
y_pred

array([[1.00699169e-04, 2.07221518e-06, 5.80573869e-06, ...,
        4.49011315e-06, 3.12605201e-06, 2.56338099e-06],
       [1.17338772e-06, 9.70885168e-07, 3.14210498e-07, ...,
        2.79634551e-07, 5.55389759e-07, 4.81651473e-06],
       [9.99513637e-01, 1.53243567e-06, 5.02507968e-06, ...,
        5.00803395e-06, 2.99843288e-06, 6.95246112e-06],
       ...,
       [1.46993804e-06, 9.99516764e-01, 8.43109444e-06, ...,
        9.26526532e-06, 6.24193107e-06, 1.42337163e-06],
       [8.06834574e-06, 7.84172368e-06, 5.64755545e-07, ...,
        6.11750680e-07, 5.44016748e-07, 8.47003255e-06],
       [3.93502446e-05, 4.37841800e-06, 1.09292525e-05, ...,
        9.23327738e-06, 5.64019614e-06, 1.28461020e-05]])

In [18]:
newdf["label"].unique()

array(['(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'AIDS',
       'Alcoholic hepatitis', 'Allergy', 'Arthritis', 'Bronchial Asthma',
       'Cervical spondylosis', 'Chicken pox', 'Chronic cholestasis',
       'Common Cold', 'Dengue', 'Diabetes ',
       'Dimorphic hemmorhoids(piles)', 'Drug Reaction',
       'Fungal infection', 'Gastroenteritis', 'GERD', 'Heart attack',
       'hepatitis A', 'Hepatitis B', 'Hepatitis C', 'Hepatitis D',
       'Hepatitis E', 'Hypertension ', 'Hyperthyroidism', 'Hypoglycemia',
       'Hypothyroidism', 'Impetigo', 'Jaundice', 'Malaria', 'Migraine',
       'Osteoarthristis', 'Paralysis (brain hemorrhage)',
       'Peptic ulcer diseae', 'Pneumonia', 'Psoriasis', 'Tuberculosis',
       'Typhoid', 'Urinary tract infection', 'Varicose veins'],
      dtype=object)

In [19]:
a = np.zeros((1, 131))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]])

In [20]:

y_pred = rfc.predict_proba(X_tes)
y_pred1 = rfc.predict(X_tes)

NameError: name 'X_tes' is not defined

In [21]:
y_pred

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.08,
        0.  , 0.  , 0.32, 0.  , 0.07, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.17, 0.  , 0.16, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.01, 0.  , 0.  , 0.  , 0.01, 0.  , 0.18, 0.  ]])

In [22]:
y_pred1

array(['Dimorphic hemmorhoids(piles)'], dtype=object)

In [25]:
joblib.dump(rfc, "rf.pkl")

['rf.pkl']

In [35]:
X_tes = [[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]]
model = pickle.load(open("D:\AI Proj\My Own Projects\RainPrediction\models\cat.pkl", "rb"))
model.predict(X_tes)

array([0], dtype=int64)